name = "tk100x-academy-api"
main = "src/index.ts"
compatibility_date = "2025-02-01"
account_id = "2d60844e25a3418f00e069d10d75e07e"

[vars]
CORS_ORIGIN = "https://tk100x.com"
# RESEND_API_KEY = "" # Add via wrangler secret
# STRIPE_WEBHOOK_SECRET = "" # Add via wrangler secret
# JWT_SECRET = "" # Add via wrangler secret

[[d1_databases]]
binding = "DB"
database_name = "tk100x-academy-db"
database_id = "92340abb-3d0e-466f-82f2-366b83161668"
